#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "❌ Direct push to main branch is not allowed."
  exit 1
fi

if [ "$branch" = "dev" ]; then
  echo "❌ Direct push to main branch is not allowed."
  exit 1
fi